FROM node:18-alpine

# Create app directory
WORKDIR /var/www/app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Install yarn global
# RUN npm install -g yarn
